apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}{{ .Values.envSuffix }}
  namespace: {{ .Values.namespace }}{{ .Values.envSuffix }}
spec:
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
