apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app-previews
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: nachog00
          repo: helm-devlab
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 60

  template:
    metadata:
      name: demo-app-pr-{{ number }}
    spec:
      project: default
      source:
        repoURL: https://github.com/nachog00/helm-devlab.git
        path: charts/demo-app
        targetRevision: '{{ head_sha }}'
        helm:
          values: |
            namespace: demo-pr-{{ number }}
            envSuffix: -pr-{{ number }}
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-pr-{{ number }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
