apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: <your-chart-name>-previews
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: <your-org>
          repo: <your-repo>
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 60

  template:
    metadata:
      name: <your-chart-name>-pr-{{ number }}
    spec:
      project: default
      source:
        repoURL: https://github.com/<your-org>/<your-repo>.git
        path: charts/<your-chart-name>
        targetRevision: '{{ head_sha }}'
        helm:
          values: |
            namespace: <your-chart-name>-pr-{{ number }}
      destination:
        server: https://kubernetes.default.svc
        namespace: <your-chart-name>-pr-{{ number }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
